name: mlflow-env
channels:
  - defaults
dependencies:
  - python=3.8
  - pip:
    - mlflow-skinny
    - scikit-learn
    - pandas
    - azure-ai-ml
    - influxdb
    - matplotlib
    - ewtpy
    - scikit-learn-intelex
