name: mlflow-env
channels:
  - defaults
dependencies:
  - python=3.8.16
  - pip:
    - attrs
    - azure-ai-ml
    - azure-common
    - azure-core
    - azure-identity
    - azure-mgmt-core
    - azure-storage-blob
    - azure-storage-file-datalake
    - azure-storage-file-share
    # - ca-certificates
    - cachetools
    - certifi
    - cffi
    - charset-normalizer
    - click
    - cloudpickle
    - colorama
    - cryptography
    - cycler
    - databricks-cli
    - entrypoints
    - ewtpy
    - fonttools
    - gitdb
    - gitpython
    - google-api-core
    - google-auth
    - googleapis-common-protos
    - idna
    - importlib-metadata
    - importlib-resources
    - influxdb
    - isodate
    - jsonschema
    - kiwisolver
    # - libffi
    - marshmallow
    - mlflow-skinny
    - msal
    - msal-extensions
    - msgpack
    - msrest
    - oauthlib
    - opencensus
    - opencensus-context
    - opencensus-ext-azure
    # - openssl
    - packaging
    - pandas
    - pillow
    - pip
    - pkgutil-resolve-name
    - portalocker
    - protobuf
    - psutil
    - pyasn1
    - pyasn1-modules
    - pycparser
    - pydash
    - pyjwt
    - pyparsing
    - pyrsistent
    - python-dateutil
    - pytz
    # - pywin32
    - pyyaml
    - requests
    - requests-oauthlib
    - rsa
    - setuptools
    - setuptools-scm
    - six
    - smmap
    # - sqlite
    - sqlparse
    - strictyaml
    - scikit-learn
    - tabulate
    - tomli
    - tqdm
    - typing-extensions
    - tzdata
    - urllib3
    - vc
    - wheel
    - zipp